* Abstract [2/2]
- [X] We then identify four ... by Google Chrome, and then write replacements ..." — drop the comma and
  "then"
- [X] translation validated in Lean" — maybe a hyphen between "translation" and "validated"?
* Introduction [3/3]
- [X] And Chrome is surely the most sophisticated Skia client: it is developed at the same company," —
  replace "it is" with "both are"
- [X] across Skia back-ends and GPUs" — maybe "across GPUs and Skia back-ends", otherwise it's a bit
  unclear what "Skia" applies to
- [X] (3) A efficient and correct Skia optimizer that applies these optimizations (Section 5)." — "An"
  not "A", or change to "correct and efficient" to preserve rhythm
* Skia [2/2]
- [X] "restricting the effect of clipRect to the enclosed commands:" — should end in a period, not a colon
- [X] Extra space in cat image footnote
* Semantics [8/8]
- [X] "objects like pairs, functions, integers, and the like" — I would drop "objects like"
- [X] "which in practice means it assumes away up to anti-aliasing and rounding." — this doesn't
  make sense, gotta say either "assumes away anti-aliasing and rounding" or "is accurate up to
  anti-aliasing and rounding"
- [X] The p in the blend_p in the top row should be italics but isn't, gotta fix that!
- [X] "Because Layer has only these two constructors (plus the special Empty layer), it is particularly easy to induct on them in proofs." — The "them" seems to refer to something in the previous sentence, just drop it
- [X] "allows instead taking the difference instead of intersecting the new mask" — similar
- [X] "which we intend to submit as an artifact," — no longer intend, write "which we submitted as an artifact"
- [X] "is 453 lines of code in total." — I assume this is out of date, just say "under a thousand"
- [X] "We also provide an instantiation of the abstract model, representing Point as a
2-tuple of reals and Color as a 4-tuple of real numbers representing premultiplied ARGB colors."
— do we?
* Rewrites [6/6]
- [X] "including pages like the Amazon, Github, New York Times, and Tiktok home pages." — more duplication
- [X] "others were specific to particular, widely-used, web frameworks" — maybe drop "widely-used" now?
- [X] "Because 𝜇Skia programs are imperative, however, equivalence does not generally allow" — Next
  sentence has another "however", let's drop this one
- [X] "using as a lemma that states as a fact that," — I'm not even sure what this was trying to say, please fix it
- [X] "This snippet draws contents of the image, and" — draws the contents
- [X] "would require this more general equation and incorrect equation:" — another one
* Compiler [4/4]
- [X] "that applies rewrites discussed in Section 4." — I would add "the" before rewrites, otherwise it sounds like we maybe apply only a subset of them.
- [X] "Some times the actions of the top most" — should be "Sometimes" with no space, and "top-most" with a hyphen (edited)
- [X] "searches the SkRecord buffer for each rewrite rule from Section 4, replacing the matched commands with the right-hand side of the rewrite rule." — this is a bit confusing because we refer to the right-hand side but not the left-hand side. Maybe we say "matched left-hand side commands"?
- [X] "this split into layers is chosen by Chrome to optimize animations" — add "is" as shown
