* Abstract [2/2]
- [X] We then identify four ... by Google Chrome, and then write replacements ..." — drop the comma and
  "then"
- [X] translation validated in Lean" — maybe a hyphen between "translation" and "validated"?
* Introduction [3/3]
- [X] And Chrome is surely the most sophisticated Skia client: it is developed at the same company," —
  replace "it is" with "both are"
- [X] across Skia back-ends and GPUs" — maybe "across GPUs and Skia back-ends", otherwise it's a bit
  unclear what "Skia" applies to
- [X] (3) A efficient and correct Skia optimizer that applies these optimizations (Section 5)." — "An"
  not "A", or change to "correct and efficient" to preserve rhythm
* Skia [2/2]
- [X] "restricting the effect of clipRect to the enclosed commands:" — should end in a period, not a colon
- [X] Extra space in cat image footnote
* Semantics [8/8]
- [X] "objects like pairs, functions, integers, and the like" — I would drop "objects like"
- [X] "which in practice means it assumes away up to anti-aliasing and rounding." — this doesn't
  make sense, gotta say either "assumes away anti-aliasing and rounding" or "is accurate up to
  anti-aliasing and rounding"
- [X] The p in the blend_p in the top row should be italics but isn't, gotta fix that!
- [X] "Because Layer has only these two constructors (plus the special Empty layer), it is particularly easy to induct on them in proofs." — The "them" seems to refer to something in the previous sentence, just drop it
- [X] "allows instead taking the difference instead of intersecting the new mask" — similar
- [X] "which we intend to submit as an artifact," — no longer intend, write "which we submitted as an artifact"
- [X] "is 453 lines of code in total." — I assume this is out of date, just say "under a thousand"
- [X] "We also provide an instantiation of the abstract model, representing Point as a
2-tuple of reals and Color as a 4-tuple of real numbers representing premultiplied ARGB colors."
— do we?
* Rewrites [6/6]
- [X] "including pages like the Amazon, Github, New York Times, and Tiktok home pages." — more duplication
- [X] "others were specific to particular, widely-used, web frameworks" — maybe drop "widely-used" now?
- [X] "Because 𝜇Skia programs are imperative, however, equivalence does not generally allow" — Next
  sentence has another "however", let's drop this one
- [X] "using as a lemma that states as a fact that," — I'm not even sure what this was trying to say, please fix it
- [X] "This snippet draws contents of the image, and" — draws the contents
- [X] "would require this more general equation and incorrect equation:" — another one
* Compiler [4/4]
- [X] "that applies rewrites discussed in Section 4." — I would add "the" before rewrites, otherwise it sounds like we maybe apply only a subset of them.
- [X] "Some times the actions of the top most" — should be "Sometimes" with no space, and "top-most" with a hyphen (edited)
- [X] "searches the SkRecord buffer for each rewrite rule from Section 4, replacing the matched commands with the right-hand side of the rewrite rule." — this is a bit confusing because we refer to the right-hand side but not the left-hand side. Maybe we say "matched left-hand side commands"?
- [X] "this split into layers is chosen by Chrome to optimize animations" — add "is" as shown

* Evaluation [9/9]
- [X] "an 8-core Apple M2 unified CPU/GPU with 16GB RAM with Skia’s “Graphite” graphics backend" — I'd replace the second "with" with "using" to avoid duplication
- [X] "do not translation validate due to" — again, I'd add a hyphen in "translation-validate"
- [X] "with differing pixels are drawn in red." — extra word
- [X] "Notably, we perform the pixel comparison to all benchmarks" — "to" to "on "
- [X] 49 benchmarks are actually affected by the optimizer, and these all see speed-ups, ranging
  from 0.99× to 3.04×." — I mean "all see speed-ups" is now false
- [X] "genuine and not influenced by noise, when the entire interval" — ok, here I do not like the comma
- [X] "which only uses the gradient mask rewrite, which uses the framework discussed in Section
4.4." I would rewrite to avoid the which-which
- [X] "Like in Graphite, the majority of the rewritten benchmarks have CI’s" — add "the" as indicated
- [X] "the solid-white fill, as its the first command in a Layer" — should be "it's"
* Discussion [3/3]
- [X] "Thus we changed our focus to develop the formalization" → "We thus changed our focus toward developing the formalization"
- [X] "SVG or HTML <canvas>" — the <canvas> should be in typewriter text.
- [X] "so that, for example, we could verify a compiler from, say," — duplicative

# - [ ] "Warnock and Geschke then founded Adobe [1], which introduced PostScript [4], then PDF [3]." — replace indicated by "and"
# - [ ] "Color blending was introduced by Porter and Duff [32]." — add indicated "was"
# - [ ] "and later work from the same authors [28] uses" — I think Emina isn't actually on the follow-on papers, so you should use the singular "author"
# - [ ] "We will be submitting two artifacts. The first being the Lean mechanization of 𝜇Skia semantics and the rewrites discussed in Section 4." — replace indicated with "is", otherwise it is not grammatical
# - [ ] "The second being our fork of Skia with our optimizer that implements the aforementioned rewrites." — Likewise, this might be a difference between Indian English and American English, dunno
# - [ ] "and the another 100 websites" — drop "an", otherwise it's doing two articles to one word
