#+title: Skia Paper

* TODO [42/42]
- [X] does not change any style or formatting settings of the template,
- [X] does not exceed the page limit specified in the acceptance-notification e-mail,
- [X] is in PDF format,
- [X] has all fonts embedded in the PDF file,
- [X] uses only scalable font types (like Type 1, TrueType) --- bit-mapped font types (like Type 3) are not acceptable,
- [X] provides the affiliation (institution and country) in the author information on the first page,
- [X] defines all authors individually (not as a list),
- [X] has the title and all headings properly capitalized,
- [X] does not use footnotes and references in the abstract,
- [X] provides a DOI for each item in the References section (if possible),
- [X] has all diagrams embedded in vector graphics
- [X] (if not possible, use a high-resolution bitmap format of at least 300 dpi; do not use JPG, but a lossless format like PNG or GIF; JPG is ok for photos),
- [X] has all text in figures and tables large enough and readable when printed,
- [X] has a caption for every figure or table,
- [X] has all units consistently separated from their values with a half space (e.g., '\SI{33}{GB}'),
- [X] has no orphans and widows,
- [X] has reduced the use of bold face and bright colors in the text as much as possible, underlining is not used at all in the text,
- [X] has all third-party material appropriately attributed (mention author, copyright holder, and origin).
- [X] The format of your paper must strictly adhere to the ACM Format.
  LaTeX: Use version acmart v2.18 or newer.
  You can directly download the LaTeX class file acmart and the BibTeX ACM Reference Format, which
  are also available from CTAN.
  Please use the 'acmsmall' style by using the following LaTeX class configuration:
  #+begin_src latex
    \documentclass[acmsmall]{acmart}
  #+end_src
- [X] Article Setup: Copy the following code into your LaTeX document before \begin{document}.
  Please note that this is specific to your paper (Word users, please insert the information in the
  appropriate fields).
  Please use a new line for each of these commands.
  #+begin_src latex
    %%% The following is specific to  and the paper
    %%% 'Semantics for 2D Rasterization'
    %%% by Bhargav Kulkarni, Henry Whiting, and Pavel Panchekha.
    %%%
    \setcopyright{cc}
    \setcctype{by}
    \acmDOI{10.1145/3839471}
    \acmYear{2026}
    \acmJournal{PACMPL}
    \acmVolume{10}
    \acmNumber{OOPSLA2}
    \acmArticle{339}
    \acmMonth{10}
    \acmSubmissionID{oopslab26main-p563-p}
    \received{2026-03-17}
    \received[accepted]{2026-08-06}
  #+end_src
- [X] Then, please copy the following code into your LaTeX document after \begin{document}.
  If you use umlauts or other unicode characters, please do not forget to add
  \usepackage[utf8]{inputenc} to the preamble of your LaTeX document.
  Please re-add linebreaks to the title and a short title if necessary.
  #+begin_src latex
    \title{Semantics for 2D Rasterization}

    \author{Bhargav Kulkarni}
    \correspondingauthor
    \orcid{0009-0008-2320-6112}
    \affiliation{%
      \institution{University of Utah}
      \city{Salt Lake City}
      \country{USA}
    }
    \email{bhargavk@cs.utah.edu}

    \author{Henry Whiting}
    \orcid{0009-0005-9559-8395}
    \affiliation{%
      \institution{University of Utah}
      \city{Salt Lake City}
      \country{USA}
    }
    \email{u1598085@utah.edu}

    \author{Pavel Panchekha}
    \orcid{0000-0003-2621-3592}
    \affiliation{%
      \institution{University of Utah}
      \city{Salt Lake City}
      \country{USA}
    }
    \email{pavpan@cs.utah.edu}
  #+end_src
  Word: Download template from ACM format site.
  Please use the 'acmsmall' style by selecting the right template.
  More information can be found on the PACMPL author guidelines.
- [X] The ACM style provides the three small sections 'CCS Concepts', 'Additional Key Words and
  Phrases', and 'ACM Reference Format' to follow the abstract; these are mandatory on the paper in
  the given order.
  Make sure you correctly classify your paper using the 2012 ACM Computing Classification System
  (CCS).
  The content of the CCS has to be picked from the provided list (with the CCS tool).
  The order of the CCS concepts is based on their relevance.
  The keywords are user-defined.
  (You should also insert the CCS XML snippet into your sources: for LaTeX documents using the
  environment 'CCSXML' and for Word documents using the properties dialog.)
- [X] During the submission of the camera-ready paper using our submission site, you need to copy
  the XML snippet from the ACM CCS tool into a text field of the submission form.
- [X] Information in running heads:
  - [X] Authors: Use the complete list of authors as long as it fits on one line in the running
    heads.
    In other words, first try to use the full author information.
    If it is longer than one line, initial the given names (and use the command \shortauthors to
    declare the short version of the author list), if still longer than one line, use only surnames,
    and only as a last resort, use et al.
    after the first author.
  - [X] Title: The title should not use more than one line in the running heads (starting on page
    3).
    If the title is too long to fit on one line, please use the beginning of the title (delete from
    the end), followed by ellipsis ("...")
    (specifying the shorter title using brackets as option argument for the \title command).
    Please note that a short title that concisely describes the contribution is always a good idea.
- [X] Acknowledgements such as "This work was partially funded by ..."
  should either go to the acknowledgements section or be formatted using the command \titlenote, but
  not as \thanks, in the ACM style acmart.
- [X] The text height must not exceed 23.5 cm. The text width must not exceed 18 cm.
- [X] Text, tables, and figures (also headings, program code, and formulas) must not run into the margins outside the text area and between the columns.
- [X] The font size is 10 pt for all body text, including acknowledgments. The references should have a font size of 8 pt.
- [X] The title should use headline-style capitalization (e.g., "The Best POPL Paper of All Time").
- [X] All levels of headings use headline-style capitalization. Headings "Acknowledgments" and "References" must not be numbered.
- [X] Third-level headings: The heading should be followed by a period and then directly by the text on the same line.
- [X] The title, authors, headings, and captions must be in sans-serif font (Biolinum). The affiliations and the body text must be in serif font (Libertine).
- [X] Captions of tables and figures must be in upright font; without horizontal lines between the caption and the body text.
- [X] (The LaTeX package 'subfig' interferes with the layout of captions. If this package is used, use '\usepackage[caption=false]{subfig}', which disables the additional caption formatting.)
- [X] Captions: Tables should have their caption above. Figures and listings should have the caption below.
- [X] Colors: ACMART typesets citations and cross-references in color. Please make sure to not change the default color settings (e.g., avoid \hypersetup{draft}).
- [X] Between tables/figures and body text, there must be some vertical white space. Figures must not be framed with an extra box. Please remove those frame boxes.
- [X] Equations and formulas should be typeset and should not be imported as pictures.
- [X] The sections at the end of the paper should be ordered as follows: first acknowledgements, then appendices, and last references.
- [X] The first reference must not run into the heading of the references section.
- [X] References: The reference text on the second and following lines should be indented.
- [X] Only for Word users: Text (with links) should be in black, not blue, and not underlined.

* Skia Examples

#+begin_src c++
void draw(SkCanvas* canvas) {
    canvas->clear(SK_ColorWHITE);

    SkPaint redPaint;
    // redPaint.setColor(SK_ColorRED);

    SkRect redRect = SkRect::MakeXYWH(0, 0, 180, 180);
    canvas->drawRect(redRect, redPaint);
}
#+end_src


#+begin_src c++
  void draw(SkCanvas* canvas) {
      canvas->clear(SK_ColorWHITE);

      SkPaint redPaint;
      redPaint.setColor(SK_ColorRED);

      SkRect redRect = SkRect::MakeXYWH(0, 0, 180, 180);
      canvas->drawRect(redRect, redPaint);
  }
#+end_src

#+begin_src c++

#+end_src

* Notes
- Hoare-style braces around an image (LaTeX snippet):
#+begin_src latex
$\left\{\vcenter{\hbox{\frame{\includegraphics[scale=0.28]{drawing0.pdf}}}}\right\}$
#+end_src

- Hoare triple helper macros with list-based image states:
#+begin_src latex
\ExplSyntaxOn

% Render one state from a comma-list of image filenames.
% Example: \hoarestatefromlist{drawing0.pdf,drawing2.pdf}
\NewDocumentCommand{\hoarestatefromlist}{m}
 {
  \begin{tabular}{c}
    \clist_set:Nn \l_tmpa_clist { #1 }
    \int_zero:N \l_tmpa_int
    \clist_map_inline:Nn \l_tmpa_clist
     {
      \int_incr:N \l_tmpa_int
      \frame{\includegraphics[scale=0.28]{##1}}
      \int_compare:nNnT { \l_tmpa_int } < { \clist_count:N \l_tmpa_clist }
       { \\[0.6em] }
     }
  \end{tabular}
 }

\NewDocumentCommand{\hoarecode}{m}
 {
  \begin{tabular}{T}
  #1
  \end{tabular}
 }

\NewDocumentCommand{\hoaretriplelist}{m m m}
 {
  \begin{figure}[H]
  \centering
  \hoarestatefromlist{#1}\quad
  \hoarecode{#2}\quad
  \hoarestatefromlist{#3}
  \end{figure}
 }

\ExplSyntaxOff
#+end_src

#+begin_src c++
  void draw(SkCanvas* canvas) {
      SkPaint paint;

      SkPoint center = {128.0f, 128.0f};
      SkScalar radius = 128.0f;

      SkColor4f colors[] = {
          SkColors::kBlack,                  // opaque black
          SkColors::kBlack.withAlpha(0.0f)   // transparent black
      };

      SkScalar positions[] = {0.0f, 1.0f};

      auto shader = SkShaders::RadialGradient(
                                              center,
                                              radius,
                                              { {colors, positions, SkTileMode::kClamp}, {} },
                                              nullptr
                                              );

      paint.setShader(shader);

    	SkPaint savePaint;
    	savePaint.setBlendMode(
                             SkBlendMode::kDstIn
                             );
      SkSamplingOptions sampling;
      canvas->drawImageRect(image, SkRect::MakeXYWH(0, 0, 256, 256), sampling);

    	canvas->saveLayer(nullptr, &savePaint);
    	canvas->drawRect(SkRect::MakeXYWH(0, 0, 256, 256), paint);
    	canvas->restore();
  }
#+end_src

#+begin_src c++
void draw(SkCanvas* canvas) {
	SkPaint paint;
  	SkPaint savePaint;
  	savePaint.setBlendMode(
		SkBlendMode::kDstIn
	);
    SkSamplingOptions sampling;
    canvas->drawImageRect(image, SkRect::MakeXYWH(0, 0, 256, 256), sampling);

  	canvas->saveLayer(nullptr, &savePaint);
  	canvas->drawRect(SkRect::MakeXYWH(0, 0, 180, 180), paint);
  	canvas->drawRect(SkRect::MakeXYWH(120, 120, 136, 136), paint);
  	canvas->restore();
}
#+end_src

#+begin_src LaTeX
\begin{figure}
  \centering
  \begin{minipage}{0.40\linewidth}
    \begin{tabular}{S}
      Layer & ::= & Empty() \\
            & |   & Draw(l: \textsf{Layer}, s: \Shape,\\
            &     & \hspace{4em}p: \textsf{Paint}, c: \Shape)\\
            & |   & BlendLayer(l\textsubscript{bot}, l\textsubscript{top}: \textsf{Layer})
            &     & \hspace{8em}p: \textsf{Paint}) \\[2pt]
      Paint & ::= & Paint(fill: Image, filter: Filter, blend: Blend)
    \end{tabular}
    \label{fig:layer}
  \end{minipage}
  \hfill
  \begin{minipage}{0.58\linewidth}
    \centering
    \begin{tabular}{S M c T}
      Command & c & ::= & Draw($g$: Shape, $p$: Paint) \\
              &   & | & DrawText(string, $p$: Paint) \\
              &   & | & Clip($cl$: Shape) \\
              &   & | & Save(); $c$; Restore() \\
              &   & | & SaveLayer($p$: Paint); $c$; Restore() \\
              &   & | & $c$; $c$ \\[1pt]
    \end{tabular}
    \caption{%
      \textsf{Layer} provides
      a simple functional description of Skia images.
    }
    \label{fig:muskia}
  \end{minipage}
\end{figure}
#+end_src

* Abstract/Intro stuff

- line 31

* Acks

Thalia Archibald
